#!/bin/bash
set -e

IMAGE="progrium/buildstep"

CMD="apt-get update && apt-get install -y supervisor && rm -rf /var/lib/apt/lists/*"

ID=$(sudo docker run -d $IMAGE /bin/sh -c "$CMD")
docker attach $ID
test $(sudo docker wait $ID) -eq 0
sudo docker commit $ID $IMAGE > /dev/null
